name: root
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf
  - affine
  - anaconda-client
  - anaconda-navigator
  - asn1crypto
  - attrs
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - bokeh
  - bottleneck
  - bzip2
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - chardet
  - click
  - click-plugins
  - cligj
  - clyent
  - colorama
  - conda
  - conda-build
  - conda-package-handling
  - contextily
  - cryptography
  - curl
  - cycler
  - decorator
  - defusedxml
  - descartes
  - entrypoints
  - expat
  - filelock
  - fiona
  - freetype
  - freexl
  - gdal
  - geographiclib
  - geopandas
  - geoplot
  - geopy
  - geos
  - glob2
  - hdf4
  - hdf5
  - html5lib
  - icu
  - idna
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyterlab
  - jupyterlab_server
  - kealib
  - kiwisolver
  - krb5
  - libarchive
  - libboost
  - libcurl
  - libgdal
  - libiconv
  - libkml
  - liblief
  - libnetcdf
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - lzo
  - markupsafe
  - matplotlib-base
  - mercantile
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mplcursors
  - munch
  - navigator-updater
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openssl
  - owslib
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pickleshare
  - pillow
  - pkginfo
  - plotly
  - proj4
  - prometheus_client
  - prompt_toolkit
  - psutil
  - py-lief
  - pycosat
  - pycparser
  - pyepsg
  - pygments
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-libarchive-c
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtpy
  - rasterio
  - requests
  - retrying
  - rtree
  - ruamel_yaml
  - scipy
  - seaborn
  - send2trash
  - shapely
  - sip
  - six
  - snuggs
  - soupsieve
  - sqlite
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xerces-c
  - xmltodict
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip
  - pip:
    - aiohttp
    - aspy-yaml
    - async-timeout
    - automat
    - cachetools
    - cfgv
    - configparser
    - constantly
    - convertdate
    - crayons
    - cssselect
    - emoji
    - emoji-data-python
    - fut
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-auth-oauthlib
    - googletrans
    - holidays
    - httplib2
    - hyperlink
    - identify
    - idna-ssl
    - importlib-metadata
    - importlib-resources
    - incremental
    - input
    - jupyter-cjk-xelatex
    - jupyter-contrib-core
    - jupyter-contrib-nbextensions
    - jupyter-highlight-selected-word
    - jupyter-latex-envs
    - jupyter-nbextensions-configurator
    - jupyter-server-proxy
    - matplotlib
    - memory-profiler
    - mtranslate
    - multidict
    - nltk
    - nodeenv
    - oauthlib
    - opencv-python
    - parsel
    - pip
    - pre-commit
    - pyasn1
    - pyasn1-modules
    - pyautogui
    - pydispatcher
    - pydotplus
    - pygetwindow
    - pyhamcrest
    - pymeeus
    - pymongo
    - pymsgbox
    - pynput
    - pyotp
    - pyrect
    - pyscreeze
    - pytweening
    - queuelib
    - regex
    - regressors
    - requests-oauthlib
    - rsa
    - scikit-learn
    - scrapy
    - selenium
    - service-identity
    - setuptools
    - simpervisor
    - sklearn
    - squarify
    - toml
    - tox
    - translate
    - twisted
    - uritemplate
    - vadersentiment
    - virtualenv
    - w3lib
    - webdriver-manager
    - wordcloud
    - xlrd
    - yarl
    - zipp
    - zope-interface


